
  const books = [
    {
      id: 1,
      title: "Atomic Habits",
      author: "James Clear",
      category: "Self Help",
      brand: "Penguin Random House",
      publisher: "Avery",
      language: "English",
      price: 499,
      discountPrice: 399,
      rating: 4.9,
      reviews: 18540,
      pages: 320,
      stock: 25,
      isbn: "9780735211292",
      publishedYear: 2018,
      coverImage: "https://images-na.ssl-images-amazon.com/images/I/91bYsX41DVL.jpg",
      description: "Atomic Habits is a bestselling self-improvement book that explains how small, consistent improvements can produce extraordinary long-term results. James Clear combines scientific research, practical techniques, and inspiring stories to help readers build positive habits, break bad ones, and create systems that lead to personal and professional success. The book focuses on improving just one percent every day and shows how tiny changes can transform health, relationships, productivity, and overall quality of life."
    },
    {
      id: 2,
      title: "The Psychology of Money",
      author: "Morgan Housel",
      category: "Finance",
      brand: "Jaico Publishing",
      publisher: "Harriman House",
      language: "English",
      price: 599,
      discountPrice: 449,
      rating: 4.8,
      reviews: 12450,
      pages: 256,
      stock: 30,
      isbn: "9780857197689",
      publishedYear: 2020,
      coverImage: "https://images-na.ssl-images-amazon.com/images/I/81Lb75rUhLL.jpg",
      description: "The Psychology of Money explores how human emotions, personal experiences, and behavior shape financial decisions more than intelligence or technical knowledge. Through engaging stories and practical lessons, Morgan Housel teaches readers about investing wisely, building wealth, avoiding financial mistakes, managing risks, and developing a healthy mindset toward money that leads to long-term financial success."
    },
    {
      id: 3,
      title: "Clean Code",
      author: "Robert C. Martin",
      category: "Programming",
      brand: "Prentice Hall",
      publisher: "Pearson",
      language: "English",
      price: 899,
      discountPrice: 749,
      rating: 4.9,
      reviews: 9800,
      pages: 464,
      stock: 15,
      isbn: "9780132350884",
      publishedYear: 2008,
      coverImage: "https://images-na.ssl-images-amazon.com/images/I/41SH-SvWPxL.jpg",
      description: "Clean Code is considered one of the most important books for software developers. Robert C. Martin explains how to write clean, readable, maintainable, and efficient code using practical examples and coding principles. It covers naming conventions, functions, classes, testing, refactoring, and best practices that help developers create professional-quality software."
    },
    {
      id: 4,
      title: "The Alchemist",
      author: "Paulo Coelho",
      category: "Novel",
      brand: "HarperOne",
      publisher: "HarperCollins",
      language: "English",
      price: 399,
      discountPrice: 299,
      rating: 4.7,
      reviews: 25000,
      pages: 208,
      stock: 40,
      isbn: "9780061122415",
      publishedYear: 1988,
      coverImage: "https://images-na.ssl-images-amazon.com/images/I/71aFt4+OTOL.jpg",
      description: "The Alchemist is a timeless novel that follows the journey of Santiago, a young shepherd who dreams of discovering treasure hidden near the Egyptian pyramids. Along the way, he learns valuable lessons about courage, destiny, love, perseverance, and following one's dreams. The novel inspires readers to believe in themselves and pursue their true purpose."
    },
    {
      id: 5,
      title: "Deep Work",
      author: "Cal Newport",
      category: "Productivity",
      brand: "Grand Central Publishing",
      publisher: "Grand Central",
      language: "English",
      price: 650,
      discountPrice: 520,
      rating: 4.8,
      reviews: 8900,
      pages: 304,
      stock: 22,
      isbn: "9781455586691",
      publishedYear: 2016,
      coverImage: "https://images-na.ssl-images-amazon.com/images/I/81JJ7fyyKyS.jpg",
      description: "Deep Work teaches readers how to develop intense focus in a world filled with constant distractions. Cal Newport explains why deep concentration is becoming increasingly valuable and provides actionable strategies for improving productivity, learning complex skills faster, and producing high-quality work while minimizing distractions from technology and social media."
    },
    {
      id: 6,
      title: "Rich Dad Poor Dad",
      author: "Robert T. Kiyosaki",
      category: "Finance",
      brand: "Plata Publishing",
      publisher: "Plata",
      language: "English",
      price: 450,
      discountPrice: 350,
      rating: 4.7,
      reviews: 32000,
      pages: 336,
      stock: 18,
      isbn: "9781612681139",
      publishedYear: 1997,
      coverImage: "https://images-na.ssl-images-amazon.com/images/I/81bsw6fnUiL.jpg",
      description: "Rich Dad Poor Dad challenges traditional ideas about money and financial success. Through the contrasting lessons of two father figures, Robert Kiyosaki explains the importance of financial education, investing, entrepreneurship, passive income, and asset building. The book encourages readers to think differently about wealth and achieving financial independence."
    },
    {
      id: 7,
      title: "Think Like a Monk",
      author: "Jay Shetty",
      category: "Self Help",
      brand: "Simon & Schuster",
      publisher: "Simon & Schuster",
      language: "English",
      price: 550,
      discountPrice: 430,
      rating: 4.8,
      reviews: 10400,
      pages: 352,
      stock: 26,
      isbn: "9781982134488",
      publishedYear: 2020,
      coverImage: "https://images-na.ssl-images-amazon.com/images/I/71QKQ9mwV7L.jpg",
      description: "Think Like a Monk combines ancient wisdom with practical advice for modern living. Jay Shetty shares lessons learned during his years as a monk to help readers reduce stress, improve focus, strengthen relationships, discover purpose, and cultivate habits that lead to a happier, healthier, and more meaningful life."
    },
    {
      id: 8,
      title: "Ikigai",
      author: "Héctor García",
      category: "Lifestyle",
      brand: "Penguin",
      publisher: "Penguin Books",
      language: "English",
      price: 499,
      discountPrice: 379,
      rating: 4.7,
      reviews: 15000,
      pages: 208,
      stock: 33,
      isbn: "9780143130727",
      publishedYear: 2016,
      coverImage: "https://images-na.ssl-images-amazon.com/images/I/81l3rZK4lnL.jpg",
      description: "Ikigai explores the Japanese philosophy of living a long, meaningful, and fulfilling life. Drawing inspiration from the residents of Okinawa, the book explains how discovering your purpose, maintaining healthy habits, building strong relationships, and finding joy in everyday activities can lead to happiness and longevity."
    },
    {
      id: 9,
      title: "The Lean Startup",
      author: "Eric Ries",
      category: "Business",
      brand: "Crown Business",
      publisher: "Currency",
      language: "English",
      price: 699,
      discountPrice: 549,
      rating: 4.6,
      reviews: 9800,
      pages: 336,
      stock: 20,
      isbn: "9780307887894",
      publishedYear: 2011,
      coverImage: "https://images-na.ssl-images-amazon.com/images/I/81-QB7nDh4L.jpg",
      description: "The Lean Startup introduces a modern approach to building successful businesses through continuous innovation, customer feedback, and rapid experimentation. Eric Ries explains how entrepreneurs can reduce risk, validate ideas quickly, develop products efficiently, and create sustainable businesses by focusing on learning instead of assumptions."
    },
    {
      id: 10,
      title: "Sapiens",
      author: "Yuval Noah Harari",
      category: "History",
      brand: "Harper",
      publisher: "Harper",
      language: "English",
      price: 799,
      discountPrice: 649,
      rating: 4.9,
      reviews: 21500,
      pages: 512,
      stock: 14,
      isbn: "9780062316097",
      publishedYear: 2015,
      coverImage: "https://images-na.ssl-images-amazon.com/images/I/713jIoMO3UL.jpg",
      description: "Sapiens presents a fascinating journey through the history of humankind, from the emergence of Homo sapiens to the modern technological world. Yuval Noah Harari explores how biology, culture, economics, religion, and science have shaped civilizations, offering readers a thought-provoking perspective on humanity's past, present, and possible future."
    }
  ];


  export default books;